Fixed how ip-list is split (':', not ',').
Place the drop-list inside the ip-list folder. It could be other types of
IPs so we want to keep them in a generically named folder.

Added --load when calling the ipload tool.

Added triggers so when you place new ipload files when instaling another
package, it automatically run ipload for you.

diff --git a/debian/iplock.postinst b/debian/iplock.postinst
--- a/debian/iplock.postinst
+++ b/debian/iplock.postinst
@@ -10,11 +10,25 @@
 #
 if [ "$1" = "configure" ]
 then
-    /usr/sbin/ipload
+    if ! /usr/sbin/ipload --load
+    then
+        echo "ERROR: the ipload command failed to load the firewall on installation."
+    fi
 
     # We add `01-iptables.conf`, make sure it is taken in account
     #
     invoke-rc.d rsyslog restart
+fi
+
+if [ "$1" = "triggered" ]
+then
+    if [ "$2" = "/usr/share/iplock/ipload" -o "$2" = "/etc/iplock/ipload" ]
+    then
+        if ! /usr/sbin/ipload --load
+        then
+            echo "ERROR: the ipload command failed to load your latest firewall."
+        fi
+    fi
 fi
 
 
