Worked on the FORWARD chain.
Added entries to get the forward, input, output to work with SNAT (need to make it work with MASQUERADE though).
Enhanced the policy & type on a per table basis in chain definitions (`[<table>:]<chain>`).
Removed the support for the table prefix. Instead the chains have a `tables = ...` parameter.
To properly support one chain under multiple tables, I added the chain reference.
Added a flag in case you want to always generate all the tables. This is useful if you have empty tables with DROP as their policy. Otherwise that's ignored (will probably be fixed at some point, though).
Properly verify each table and chain is defined once at the most (err if a second instance is found).
Added a table description parameter.
Added all the -j <target> supported by iptables (although a few are still incomplete in terms of extra options).
Started moving rule doc. from README.md to the ipload.5 man page.
Updated documentations.

diff --git a/scripts/showfw b/scripts/showfw
--- a/scripts/showfw
+++ b/scripts/showfw
@@ -36,11 +36,17 @@ do
 		echo
 		echo "  -4                    to display the IPv4 tables, this is the default"
 		echo "  -6                    to display the IPv6 tables"
+		echo "  --filter              to display the filter tables, this is the default"
 		echo "  -h | --help           print out this help screen"
 		echo "  -l | --line-numbers   show line numbers (rule position)"
-		echo "  --filter              to display the filter tables, this is the default"
 		echo "  --nat                 to display the nat tables"
 		exit 0
+		;;
+
+	*)
+		echo "error: unsupported command line option $1"
+		echo "error: try --help for more information."
+		exit 1
 		;;
 
 	esac
